theme: jekyll-theme-cayman
title: The Iowa Action Desk
description: Low-tech civic routing infrastructure centered on economic solidarity and structural community advocacy.
baseurl: "/iowa-action-desk"
show_downloads: false
google_analytics:
permalink: /:path/

# Mobile Branding and Social Graph Assets
logo: "https://mmonfils.github.io/iowa-action-desk/favicon.png"
image: "https://mmonfils.github.io/iowa-action-desk/thumbnail.jpg"
url: "https://mmonfils.github.io"

# Force the GitHub Pages compiler to load SEO engines explicitly
plugins:
  - jekyll-seo-tag