theme: jekyll-theme-cayman
title: The Iowa Action Desk
description: Low-tech civic routing infrastructure centered on economic solidarity and structural community advocacy.
baseurl: "/iowa-action-desk"
show_downloads: false
google_analytics:
permalink: /:path/

# Mobile Branding and Social Graph Assets
favicon: /favicon.png
thumbnail: /thumbnail.jpg
url: "[https://mmonfils.github.io](https://mmonfils.github.io)"